name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: sanityTest
      id: sanitytest
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: sanityTest
        setup-command: ''
        command: gradle test --tests TestProgram7.sanityTest
        timeout: 10
        max-score: 2
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SANITYTEST_RESULTS: "${{steps.sanitytest.outputs.result}}"
      with:
        runners: sanitytest
